version: 2

build:
  os: ubuntu-24.04
  apt_packages:
    - swig
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - python docs/rtd_build.py

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false
