name: Code Coverage

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

env:
  BUILD_TYPE: Debug
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Dependencies
      run: sudo apt install lcov libgmock-dev libgtest-dev libyaml-cpp-dev swig -y

    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DWITH_CODE_COVERAGE=ON

    - name: Build
      run: cmake --build build

    - name: Tests
      working-directory: ${{ github.workspace }}/build
      run: ctest -V
    
    - name: Generate And Upload Code Coverage Results
      working-directory: ${{ github.workspace }}/build
      run: |
        lcov --directory . --capture --output-file coverage.info --ignore-errors mismatch --rc geninfo_unexecuted_blocks=1
        lcov --extract coverage.info '*/src/api/*' --output-file coverage_api.info
        lcov --extract coverage.info '*/src/impl/*' --output-file coverage_impl.info
        bash <(curl -s https://codecov.io/bash) -f coverage_api.info -F api || echo "Codecov did not collect API coverage reports"
        bash <(curl -s https://codecov.io/bash) -f coverage_impl.info -F impl || echo "Codecov did not collect IMPL coverage reports"
